CREATE WAREHOUSE IF NOT EXISTS COMPUTE_WH WITH WAREHOUSE_SIZE = 'X-SMALL';
CREATE DATABASE IF NOT EXISTS BLACKSWAN_DB;
CREATE SCHEMA IF NOT EXISTS BLACKSWAN_DB.RAW;

USE DATABASE BLACKSWAN_DB;
USE SCHEMA RAW;

CREATE OR REPLACE FILE FORMAT JSON_FORMAT
  TYPE = 'JSON'
  STRIP_OUTER_ARRAY = TRUE;


  