CREATE OR REPLACE STORAGE INTEGRATION S3_INT
  TYPE = EXTERNAL_STAGE
  STORAGE_PROVIDER = 'S3'
  ENABLED = TRUE
  STORAGE_AWS_ROLE_ARN = 'arn:aws:iam::982081062053:role/blackSwan'
  STORAGE_ALLOWED_LOCATIONS = ('s3://blackswan-market-pipeline/'); -- Bucket name

  DESC STORAGE INTEGRATION S3_INT;

  CREATE OR REPLACE STAGE MY_S3_STAGE
  URL = 's3://blackswan-market-pipeline/'
  STORAGE_INTEGRATION = S3_INT
  FILE_FORMAT = JSON_FORMAT;

  LIST @MY_S3_STAGE;