# .github/workflows/ci.yml
name: Black Swan CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  quality-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v1

      - name: Set up Python
        run: uv python install 3.12

      - name: Install dependencies
        run: uv pip install -r requirements.txt

      - name: Install Ruff
        run: uv pip install ruff

      - name: Run Linter
        run: uv run ruff check .

      - name: Run Formatter Check
        run: uv run ruff format --check .
